// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgSmOP_0oB0vRH89rw7qhep8-M33OOOPk',
    appId: '1:1077807028936:web:0a480937bf794a8638a3fd',
    messagingSenderId: '1077807028936',
    projectId: 'stockgap2026',
    authDomain: 'stockgap2026.firebaseapp.com',
    storageBucket: 'stockgap2026.firebasestorage.app',
    measurementId: 'G-T5E72SJZ40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx1tPfuN5e6G8tNF3gkFpkRa0lse32IjU',
    appId: '1:1077807028936:android:e27b55bf7205d14e38a3fd',
    messagingSenderId: '1077807028936',
    projectId: 'stockgap2026',
    storageBucket: 'stockgap2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVTSHmqzv4MWwn32BVZS2fkoBneCtJzdI',
    appId: '1:1077807028936:ios:07376dd9b301ee0838a3fd',
    messagingSenderId: '1077807028936',
    projectId: 'stockgap2026',
    storageBucket: 'stockgap2026.firebasestorage.app',
    iosBundleId: 'com.example.stockgap2026',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgSmOP_0oB0vRH89rw7qhep8-M33OOOPk',
    appId: '1:1077807028936:web:c78760e94c97396838a3fd',
    messagingSenderId: '1077807028936',
    projectId: 'stockgap2026',
    authDomain: 'stockgap2026.firebaseapp.com',
    storageBucket: 'stockgap2026.firebasestorage.app',
    measurementId: 'G-X1WV80DJWN',
  );
}
